// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package example

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Scoreboard struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
