// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package example

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO scoreboards (
    id, name, created_at, updated_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, created_at, updated_at
`

type CreateParams struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Scoreboard, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Scoreboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM scoreboards
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, name, created_at, updated_at FROM scoreboards
WHERE id = $1 LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id pgtype.UUID) (Scoreboard, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i Scoreboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, name, created_at, updated_at FROM scoreboards
ORDER BY name
`

func (q *Queries) List(ctx context.Context) ([]Scoreboard, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scoreboard
	for rows.Next() {
		var i Scoreboard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE scoreboards
SET name = $2, updated_at = $3
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateParams struct {
	ID        pgtype.UUID
	Name      string
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Scoreboard, error) {
	row := q.db.QueryRow(ctx, update, arg.ID, arg.Name, arg.UpdatedAt)
	var i Scoreboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
