// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package scoreboard

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Scoreboard struct {
	ID        uuid.UUID
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
