// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            uuid.UUID
	Email         string
	Name          pgtype.Text
	GivenName     pgtype.Text
	FamilyName    pgtype.Text
	Picture       pgtype.Text
	EmailVerified bool
	Locale        pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
